# Generated by Django 3.1.3 on 2022-02-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryNumber',
            fields=[
                ('date', models.DateTimeField()),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('n1', models.IntegerField()),
                ('n2', models.IntegerField()),
                ('n3', models.IntegerField()),
                ('n4', models.IntegerField()),
                ('n5', models.IntegerField()),
                ('n6', models.IntegerField()),
                ('n7', models.IntegerField()),
            ],
        ),
    ]
